---

ansible_host: "194.87.107.68"
ansible_ssh_user: "mftiedu"
ansible_ssh_pass: !vault |
                  $ANSIBLE_VAULT;1.1;AES256
                  64303030303565303163646432616232376532623366303061663663666332333265393966306266
                  3733666537333864343635663963646636306564303335640a313731396539633834396433653431
                  37323030643930623630376535653432393233366163316461613634663766383832613462666439
                  3135303934353433620a636332336537326438356135623836386138653563316437343334363064
                  3066
ansible_sudo_pass: !vault |
                   $ANSIBLE_VAULT;1.1;AES256
                   64303030303565303163646432616232376532623366303061663663666332333265393966306266
                   3733666537333864343635663963646636306564303335640a313731396539633834396433653431
                   37323030643930623630376535653432393233366163316461613634663766383832613462666439
                   3135303934353433620a636332336537326438356135623836386138653563316437343334363064
                   3066
---
